#!/bin/bash
#                          # Use Bash Shell
#$ -V                     # Inherit the submission environment
#$ -cwd                   # Start job in  submission directory
#$ -N SHF                 # Job Name
#$ -j y                   # Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID  # Name of the output file (eg. myMPI.oJobID)
#$ -pe 16way 16           # Requests 16 cores/node, 16 cores total
#$ -q development         # Queue name
#$ -l h_rt=02:00:00       # Run time (hh:mm:ss) - 1.5 hours
#$ -M                     # Email notification address (UNCOMMENT)
#$ -m be                  # Email at Begin/End of job  (UNCOMMENT)
#$ -A TG-PHY090030
export OMP_NUM_THREADS=16
./SHF         # Run the executable
