#!/bin/bash
#----------------------------------------------------
# Job script
#----------------------------------------------------

#SBATCH -J SHF                # Job name
#SBATCH -o SHF.%j.out         # Name of stdout output file (%j expands to jobId)
#SBATCH -p normal             # Queue name
#SBATCH -N 1                  # Total number of nodes requested (16 cores/node)
#SBATCH -n 1                  # Total number of mpi tasks requested
#SBATCH -t 24:00:00           # Run time (hh:mm:ss)

#SBATCH -A TG-PHY090030       # Allocation name to charge job against

export MKL_MIC_ENABLE=1
export MKL_MIC_WORKDIVISION0=1 MKL_MIC_WORKDIVISION1=0
export OMP_NUM_THREADS=16
./SHF
